### ISSUE TITLE
autoload.php requirement throws fatal error because file not exists

### ISSUE THREAD

**Issue by jphorn** [jdevalk/fewer-tags#4]
https://github.com/Emilia-Capital/fewer-tags/blob/65824fcdcf167a2fddd16c9092078c9be359dc91/fewer-tags.php#L50

```[11-Dec-2023 14:34:30 UTC] PHP Fatal error:  require(): Failed opening required '~/Sites/example.com/wp-content/plugins/fewer-tags/vendor/autoload.php' (include_path='.:/Applications/MAMP/bin/php/php7.4.21/lib/php') in ~/Sites/example.com/wp-content/plugins/fewer-tags/fewer-tags.php on line 50```

**Comment by Eroan** [comment]
Hi Joost, I confirm that the 1.3 version available on WordPress official repo tries to include a non existing autoload.php file in /vendor/.

Makes the whole site go in 500 error.

Thanks for your job there, really valuable plugin 🙏

**Comment by jdevalk** [comment]
Should be fixed with 1.3.3, really sorry about that!
